# Generated by Django 3.2.6 on 2021-08-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vickytest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, default=False, max_length=10, null=True)),
                ('lastname', models.CharField(blank=True, default=False, max_length=10, null=True)),
                ('email', models.CharField(blank=True, default=False, max_length=20, null=True)),
                ('saction', models.IntegerField(blank=True, default=False, null=True)),
            ],
        ),
    ]
